- name: Install the NFS Server Utilities and services.
  yum: pkg={{ item }} state=latest
  with_items:
   - "{{ nfsutils_pkg }}"
- name: Copy the export file to the remote server
  copy: src=exports.template dest=/etc/exports owner=root group=root mode=644
  notify:
  - StartServerServices

