--- #  NFS SERVER PLAYBOOK
- hosts: appserver
  user: test
  sudo : yes
  connection: ssh
  gather_facts: yes
  vars:
    distribution: RedHat
    nfsutils_pkg: nfs-utils
    nfslibs_pkg: nfs-utils-lib
    nfsserver_service: nfs-server
    nfslock_service: nfs-lock
    nfsmap_service: nfs-idmap
    rpcbind_service: rpcbind
    export_path: /var/share
  tasks:
  - name: Install the NFS server and utilities
    yum: pkg=nfs-utils state=latest
  - name: Copy the export fie to the remote server
    copy: src=files/exports.template dest=/etc/exports owner=root group=root mode=644
  - name: Start the RPC Bind SErvice
    service: name=rpcbind state=started
  - name: Start the RPC SErvice
    service: name=nfs-server state=started
  - name: Start the Lock SErvice
    service: name=nfs-lock state=started
  - name: Start the NFS map SErvice
    service: name=nfs-idmap state=started
  - name: Install the NFS Client and utilities
    yum: pkg=nfs-utils state=latest
    delegate_to: 127.0.0.1
  - name: Start service for Client RPC
    service: name=rpcbind state=started
    delegate_to: 127.0.0.1
  - name: Start NFS Client File Lock Service
    service: name=nfs-lock state=started
    delegate_to: 127.0.0.1
  - name: Start the NFS Clinet map SErvice
    service: name=nfs-idmap state=started
    delegate_to: 127.0.0.1
  - name: Create Client Mount directory
    file: path=/mnt/remote state=directory mode=755
    delegate_to: 127.0.0.1
  - name: Mount the filesystem on the client from the NFS server
    mount: name=/mnt/remote src=/var/share fstype=nfs state=present
    delegate_to: 127.0.0.1


