--- # MAster playbook for webservers
- hosts: '{{ hosts }}'
  user: '{{ user }}'
  sudo: yes
  connection: ssh
  pre_tasks:
  - name: When did the role run
    raw: date > /home/test/startofrole.log
  roles:
  - { role: '{{ role }}', when: "ansible_os_family == 'RedHat'" }
  post_tasks:
  - name: When did the role end
    raw: date > /home/test/endofrole.log 
