--- # MAster playbook demonstrating the delegateto command
- hosts: apacheweb
  user: test
  sudo: yes
  connection: ssh
  pre_tasks:
  - name: Ping the application server
    local_action: raw ping -c 4 satishdasi4.mylabserver.com > /home/test/Playbooks/Roles/roles/ping.out 
  roles:
   - webservers
