--- # Outline to Playbook Translation
- hosts: apacheweb
  user: test
  sudo: yes
  gather_facts: no
  tasks:
  - name: date/time stamp for when the playbook starts
    command: /usr/bin/date
    register: timestamp_start
  - debug: var=timestamp_start
  - name: Install the apache web server
    yum: pkg=httpd state=installed
    notify: start HTTPD
  - name: install telnet client software
    yum: pkg=telnet state=latest
  - name: install lynx
    yum: pkg=lynx state=latest
  - name: Log all the package installed on the system
    raw: yum list installed >/home/test/installed.log
  - name: date/time stamp for when the playbook ends
    command: /usr/bin/date
    register: timestamp_end
  - debug: var=timestamp_end 
  handlers:
  - name: start HTTPD
    service: name=httpd state=restarted
