- name: Install the mariabdb packages { client and the server)
  yum: pkg={{ item }} state=latest
  with_items:
  - "{{ dbserver_pkg }}"
  - "{{ dbclient_pkg }}"
  notify:
  - StartDBService
  - RunSecureInstallPause
  - RestartDBService
  - CopyBkupFile
  - CreatRemoteDB
  - DisplayCreationResults
  - RestoreRemoteDB
  - TestDBResults
  - ShowDBResults
- name: Add a backup cronjob to run everyday at midnight
  cron: name="DBBackup" minute="0" hour="0" job="mysqldump -u root -ppassword123 --databases {{ dbinstancename }} > dbbkup.sql"

