- hosts: appserver
  vars:
    control_server: satishdasi3.mylabserver.com
    web_root: /var/www/html    
  tasks:
  - name: Install Lynx on App Servers
    yum: pkg=lynx state=installed update_cache=true
